<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmergencyCart.Application\EmergencyCart.Application.csproj" />
    <ProjectReference Include="..\EmergencyCart.Domain\EmergencyCart.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AccountContext\" />
    <Folder Include="SharedContext\" />
  </ItemGroup>

</Project>
