// <auto-generated />
using System;
using EmergencyCart.Infrastructure.SharedContext.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmergencyCart.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831161821_v1-userCodeTableIsRequired")]
    partial class v1userCodeTableIsRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmergencyCartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("INT")
                        .HasColumnName("ExpectedQuantity");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_CartItem");

                    b.HasIndex("EmergencyCartId");

                    b.HasIndex("ItemId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.EmergencyCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("IsActive");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Location");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_EmergencyCart");

                    b.HasIndex("SectorId");

                    b.ToTable("EmergencyCart", (string)null);
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("INT")
                        .HasColumnName("Category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PK_Item");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PK_Sector");

                    b.ToTable("Sector", (string)null);
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("IsActive");

                    b.Property<int>("Roles")
                        .HasColumnType("INT")
                        .HasColumnName("Role");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Code");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.CartItem", b =>
                {
                    b.HasOne("EmergencyCart.Domain.AccountContext.Entities.EmergencyCart", "EmergencyCart")
                        .WithMany("CartItems")
                        .HasForeignKey("EmergencyCartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmergencyCart.Domain.AccountContext.Entities.Item", "Item")
                        .WithMany("CartItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmergencyCart");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.EmergencyCart", b =>
                {
                    b.HasOne("EmergencyCart.Domain.AccountContext.Entities.Sector", "Sector")
                        .WithMany("EmergencyCarts")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.User", b =>
                {
                    b.OwnsOne("EmergencyCart.Domain.AccountContext.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("I_User_Email_Address");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("EmergencyCart.Domain.AccountContext.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("EmergencyCart.Domain.AccountContext.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Hash");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.EmergencyCart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.Item", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EmergencyCart.Domain.AccountContext.Entities.Sector", b =>
                {
                    b.Navigation("EmergencyCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
